#!/bin/sh

if [ -z "$1" ]; then
  echo "Enter environment (development, test, production):"
  read environment
else
  environment=$1
fi

if [ "$environment" != "development" ] && [ "$environment" != "test" ] && [ "$environment" != "production" ]; then
  echo "Invalid environment specified, quitting."
  exit 1
fi

EDITOR="code --wait" rails credentials:edit --environment=$environment